### ISSUE TITLE
Wildcards / namespaces support

### ISSUE THREAD

**Issue by martin8801** [jfhbrook/pyee#47]
Would you consider adding support for wildcards / namespaces, as seen in the Node eventemitter2 package?

**Comment by jfhbrook** [comment]
I've been mulling this over for a few years, and I think the answer to this is no. I feel like the EE abstraction doesn't scale well to this kind of use, and there are other patterns that can be used to meet the same requirements.

For example, instead of:

```py
ee.on("pip.install", pip_install_handler)
ee.on("pip.update", pip_update_handler)
ee.on("npm.install", npm_install_handler)
ee.on("npm.update", npm_update_handler)

ee.on("*.install", any_install_handler)
ee.on("npm.*", any_npm_handler)
```

you can do:

```py
pkg.pip.on("install", pip_install_handler)
pkg.pip.on("update", pip_update_handler)
pkg.npm.on("install", npm_install_handler)
pkg.npm.on("update", npm_update_handler)

pkg.on("install", any_install_handler)
pkg.npm.on("command", any_npm_handler)
```

I'm going to keep this open so that it's easy for people to find and/or argue with me, but yeah, no.

**Comment by jfhbrook** [comment]
Closing this as a matter of housekeeping. Hopefully people will find it in closed issues.
